const CHANGE_ACTIVITY = "CHANGE_ACTIVITY";
const EXPLORE_LOCATION = "EXPLORE_LOCATION";
const TOGGLE_TIMER = "TOGGLE_TIMER";
const TICK_TIMER = "TICK_TIMER";
const ASSIGN_TIMER_ID = "ASSIGN_TIMER_ID";
const RESET_TIMER = "RESET_TIMER";
const APPLY_REWARD = "APPLY_REWARD";
const UPDATE_ACTIVITY_TICKERS = "UPDATE_ACTIVITY_TICKERS"

export { 
    CHANGE_ACTIVITY, 
    EXPLORE_LOCATION, 
    TOGGLE_TIMER, 
    TICK_TIMER,
    ASSIGN_TIMER_ID,
    RESET_TIMER,
    APPLY_REWARD,
    UPDATE_ACTIVITY_TICKERS
};