const UPDATE_GRID = "UPDATE_GRID";
const SELECT_TILE = "SELECT_TILE";
const CONTROL_TILE = "CONTROL_TILE";
const EXPLORE_TILE = "EXPLORE_TILE";
const UNSELECT_TILE = "UNSELECT_TILE";
const BUILD_HOUSE = "BUILD_HOUSE";
const ASSIGN_WORKER = "ASSIGN_WORKER";
const UPDATE_STYLE = "UPDATE_STYLE";

export {
    UPDATE_GRID,
    SELECT_TILE,
    CONTROL_TILE,
    EXPLORE_TILE,
    UNSELECT_TILE,
    BUILD_HOUSE,
    ASSIGN_WORKER,
    UPDATE_STYLE
};