const UPDATE_GRID = "UPDATE_GRID";
const SELECT_TILE = "SELECT_TILE";
const CONTROL_TILE = "CONTROL_TILE";
const EXPLORE_TILE = "EXPLORE_TILE";
const UNSELECT_TILE = "UNSELECT_TILE";
const UPDATE_STYLE = "UPDATE_STYLE";
const UPDATE_GATHERING_NODE = "UPDATE_WOODCUTTING_NODE";
const UPDATE_CURRENT_GATHERING_NODE_COORDS = "UPDATE_CURRENT_GATHERING_NODE_COORDS";

export {
    UPDATE_GRID,
    SELECT_TILE,
    CONTROL_TILE,
    EXPLORE_TILE,
    UNSELECT_TILE,
    UPDATE_STYLE,
    UPDATE_GATHERING_NODE,
    UPDATE_CURRENT_GATHERING_NODE_COORDS
};