const TICK_TIMER = "TICK_TIMER";
const RESET_TIMER = "RESET_TIMER";
const APPLY_REWARD = "APPLY_REWARD";
const UPDATE_ACTIVITY_TICKERS = "UPDATE_ACTIVITY_TICKERS";
const UPDATE_WORKERS = "UPDATE_WORKERS";

export { 
    TICK_TIMER,
    RESET_TIMER,
    APPLY_REWARD,
    UPDATE_ACTIVITY_TICKERS,
    UPDATE_WORKERS,
};