const TICK_GLOBAL_TIMER = "TICK_GLOBAL_TIMER";
const RESET_GLOBAL_TIMER = "RESET_GLOBAL_TIMER";
const APPLY_REWARD = "APPLY_REWARD";
const TICK_ACTIVITY_TIMER = "TICK_ACTIVITY_TIMER";
const RESET_ACTIVITY_TIMER = "RESET_ACTIVITY_TIMER";
const STOP_ACTIVITY_TIMER = "STOP_ACTIVITY_TIMER";
const START_ACTIVITY_TIMER = "START_ACTIVITY_TIMER";
const SET_ACTIVITY = "SET_ACTIVITY";
const SET_ACTIVITY_PARAMS = "SET_ACTIVITY_PARAMS";
const SET_ACTIVITY_DELEGATE = "SET_ACTIVITY_DELEGATE";
const SET_ACTIVITY_THRESHOLD = "SET_ACTIVITY_THRESHOLD";

export {
    TICK_GLOBAL_TIMER,
    RESET_GLOBAL_TIMER,
    APPLY_REWARD,
    TICK_ACTIVITY_TIMER,
    RESET_ACTIVITY_TIMER,
    STOP_ACTIVITY_TIMER,
    START_ACTIVITY_TIMER,
    SET_ACTIVITY,
    SET_ACTIVITY_PARAMS,
    SET_ACTIVITY_DELEGATE,
    SET_ACTIVITY_THRESHOLD
};