const UPDATE_HOUSING_GRID = "UPDATE_HOUSING_GRID";
const SELECT_TILE = "SELECT_TILE";
const CONTROL_TILE = "CONTROL_TILE";
const EXPLORE_TILE = "EXPLORE_TILE";
const UNSELECT_TILE = "UNSELECT_TILE";
const BUILD_HOUSE = "BUILD_HOUSE";
const ASSIGN_WORKER = "ASSIGN_WORKER";

export {
    UPDATE_HOUSING_GRID,
    SELECT_TILE,
    CONTROL_TILE,
    EXPLORE_TILE,
    UNSELECT_TILE,
    BUILD_HOUSE,
    ASSIGN_WORKER
};