const UPDATE_HOUSING_GRID = "UPDATE_HOUSING_GRID";
const SELECT_TILE = "SELECT_TILE";
const PURCHASE_TILE = "PURCHASE_TILE";
const UNSELECT_TILE = "UNSELECT_TILE";

export {
    UPDATE_HOUSING_GRID,
    SELECT_TILE,
    PURCHASE_TILE,
    UNSELECT_TILE
};