const APPLY_MINING_XP = "APPLY_MINING_XP";
const APPLY_WOODCUTTING_XP = "APPLY_WOODCUTTING_XP";
const RESET_HAS_LEVELLED_UP = "RESET_HAS_LEVELLED_UP";

export {
    APPLY_MINING_XP,
    APPLY_WOODCUTTING_XP,
    RESET_HAS_LEVELLED_UP,
}